name: jv_analysis
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib=3.4.3  # Downgraded Matplotlib
  - scipy
  - pyserial
  - pyvisa
  - pyvisa-py
  - tk  # Required for Tkinter
  - openpyxl
  - xlrd
  - pyqt  # Install PyQt from Conda, not pip!
  - pip
  - pip:
      - PyQtVisa  # Only install this via pip
